// Compiles the plugin runtime to two self-contained IIFEs and embeds them as strings, so the host
// can inline them into the sandbox document (the CSP there allows inline script only — no modules,
// no imports, no network).
//
// It also generates the ambient `popcraft` global that plugin authors reference. That file is
// derived from PopCraftApi / PopCraftUiApi — the types of the objects the runtime actually builds —
// which is what stops the published types drifting from the shipped behaviour.

import { build } from 'esbuild'
import { mkdirSync, writeFileSync } from 'node:fs'

mkdirSync('src/generated', { recursive: true })

async function bundle(entry) {
  const out = await build({
    entryPoints: [entry],
    bundle: true,
    format: 'iife',
    target: 'es2017',
    platform: 'browser',
    write: false,
    legalComments: 'none',
  })
  return out.outputFiles[0].text.trim()
}

const [main, ui] = await Promise.all([
  bundle('src/runtime/main.entry.ts'),
  bundle('src/runtime/ui.entry.ts'),
])

const banner = '// Generated by scripts/build.mjs from src/runtime — do not edit.\n'
writeFileSync(
  'src/generated/runtime.ts',
  banner +
    '\n/** The `popcraft` global for a plugin main script, as injectable inline script. */\n' +
    `export const MAIN_RUNTIME = ${JSON.stringify(main)}\n` +
    '\n/** The `popcraft` shim for a plugin UI document, as injectable inline script. */\n' +
    `export const UI_RUNTIME = ${JSON.stringify(ui)}\n`,
)

writeFileSync(
  'src/generated/global.d.ts',
  banner +
    `
import type { PopCraftApi } from '../runtime/main.js'
import type { PopCraftUiApi } from '../runtime/ui.js'

declare global {
  /**
   * The PopCraft plugin API.
   *
   * In a plugin's main script this is the full API (nodes, selection, styles, variables, export,
   * storage, widgets, events). In a plugin's UI document it is the message shim
   * (\`postMessage\`, \`onmessage\`, \`close\`).
   */
  const popcraft: PopCraftApi & PopCraftUiApi
  /** @deprecated Pre-rename alias for \`popcraft\`. */
  const vizpops: PopCraftApi & PopCraftUiApi
}

export {}
`,
)

console.log(`runtime: main ${main.length}B, ui ${ui.length}B`)
